### PR TITLE
Upgrade to common 0.6.0

### PR DESCRIPTION
**Pull request by stefanoborini**

### CODE REVIEW

**Comment by stefanoborini** [comment]
This PR needs to be tested in an environment with numerrin license before release.

**Comment by stefanoborini** [comment]
@khiltunen I am upgrading to 0.6.0, it should pass as well.

**Comment by khiltunen** [comment]
I made some changes to get it work with 0.5 (actually used 0.6) common. Tests and examples are passed. Ok to merge.

**Comment by stefanoborini** [comment]
@khiltunen I am going to merge and after this, I am going to do a new release. Please let me know if anything prevents me to do so at this stage.

**Comment by khiltunen** [comment]
As stated OK to merge and for new release

**Pull request merged**
